### ISSUE TITLE
Reference comment feature

### ISSUE THREAD

**Issue by nekova** [nekova/wi-wi#1]
#1 のような感じでreferenceさせるか comment#1 でreferenceさせるか

**Comment by storkibis** [comment]
シンプルに #1 が良いと思う

**Comment by nekova** [comment]
[![OK](http://www.lgtm.in/p/IUZfVN5Yp)](http://www.lgtm.in/i/IUZfVN5Yp)

**Comment by nekova** [comment]
[![LGTM](http://www.lgtm.in/p/wQ6nHXcxn)](http://www.lgtm.in/i/wQ6nHXcxn)

**Comment by storkibis** [comment]
wi-wiのヘッダに隠れる
http://wi-wi.herokuapp.com/posts/1#comment-1

**Comment by nekova** [comment]
Fix! thanks :+1:

**Comment by nekova** [comment]
うわ これproductionだと直ってない

**Comment by nekova** [comment]
Done......  :crying_cat_face:

**Comment by storkibis** [comment]
コメントNoは、すべてのPostで１つの番号が振られているけど、Post毎にナンバリングしたほうが良くないですか

**Comment by nekova** [comment]
ゲッ.......(こういう時ReopenしてもらってOKです)

**Comment by nekova** [comment]
Done
Fix なら Closeしてください :smirk_cat:

**Comment by storkibis** [comment]
closeのさせ方がわからんぞ
