### ISSUE TITLE
Post一覧のページにソート機能を追加する

### ISSUE THREAD

**Issue by storkibis** [nekova/wi-wi#4]
下記の値でソートしたいです
・投稿時間
・コメント数

**Comment by nekova** [comment]
:+1: I agree completely
new / hot / best あたりですかね
Like button(RedditやHNで言うKarma) の実装とどちらを先にやるか悩みどころ........

**Comment by storkibis** [comment]
その場合Like buttonって、Postに対してするもの？それともCommentに対してするもの？
どっちにしても、Like buttonを先に追加したほうが良さそうかと思います。
そのほうが面白そうだし、Like buttonのクリック数でソートする場合、これないとできないし。
new / hot / best あたりですね

**Comment by nekova** [comment]
new はいつまでを, hotはどういう基準で とかは全体を見て設計しないとごちゃごちゃして要らない機能になってしまうので Like からやるのに賛成です
ちなみにLikeはComment と Post それぞれ別のものがあって それぞれがUserに足されて.........
ちょっと実装まで時間欲しいです :octocat:

**Comment by nekova** [comment]
Done :smirk_cat: 

new = created_at
hot = updated_at (後々 vote と組み合わせて色々計算したい)
best = vote_score
