### ISSUE TITLE
Deleteをするときは確認ダイアログを表示する

### ISSUE THREAD

**Issue by storkibis** [nekova/wi-wi#5]
Postをdeleteする時、deleteのリンクをクリックするだけで、deleteできてしまった。
deleteする場合は、１クッションかませた方がよいと思う。
間違ってクリックした時のために。
大抵は確認ダイアログを表示して確認させてる。

**Comment by nekova** [comment]
後々, 消すボタンをちょっと押しづらくする +  消した後に 「取り消す？」 ってやんわり確認するようにしたい
