### ISSUE TITLE
Like or upvote&downvote?

### ISSUE THREAD

**Issue by nekova** [nekova/wi-wi#6]
Like only にするか upvote と downvote にするか

**Comment by nekova** [comment]
個人的にはdownvoteも欲しい

**Comment by storkibis** [comment]
確かに、downvoteもあったほうがいいかも。
あまりにもdownvote多ければ、デフォルトで非表示になったりね。

**Comment by nekova** [comment]
今である必要はないですけど, PostやCommentへのdownvoteをUserのreputation(RedditやHNでいうKarma)に反映した時のUserの行動制限をどうするかとかも考えた方がいいですね
stackoverflowはreputationがある程度ないと投票出来ないとかそんな感じだった気がします

**Comment by storkibis** [comment]
reputationによって、ユーザの権限が変わるのか。
この辺の設計って難しそう。
メカニズムデザインっぽい分野っすな。
どんなふうにしたいかもう少し具体的に検討しないと決まらないかな。
とりあえずは、reputationを表示するだけにしとけばいいか。

**Comment by nekova** [comment]
実装中 https://github.com/nekova/wi-wi/pull/8

**Comment by nekova** [comment]
vote 実装したら一気に重くなった.........

**Comment by nekova** [comment]
upvote requires 15 reputation and downvote requires 125 reputation in stackoverflow :imp:
I wanted to vote for reference, but I can't lol

**Comment by nekova** [comment]
Done! :smirk_cat: 
Viewは後で一気に直したい(今CSSの設計本読んでるので...... :bow:

**Comment by nekova** [comment]
vote score を DBから一々取ってくるんじゃなくてcacheするようにしたら早くなった

**Comment by storkibis** [comment]
なるほど、投稿した人はvoteできないのか。
